// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new chat API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for chat API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteRoomID(params *DeleteRoomIDParams, opts ...ClientOption) (*DeleteRoomIDOK, error)

	GetStreamID(params *GetStreamIDParams, opts ...ClientOption) error

	PostRoomID(params *PostRoomIDParams, opts ...ClientOption) (*PostRoomIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteRoomID deletes a room

Delete the room
*/
func (a *Client) DeleteRoomID(params *DeleteRoomIDParams, opts ...ClientOption) (*DeleteRoomIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteRoomIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteRoomID",
		Method:             "DELETE",
		PathPattern:        "/room/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteRoomIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteRoomIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for DeleteRoomID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetStreamID streams messages

Stream messages from a room
*/
func (a *Client) GetStreamID(params *GetStreamIDParams, opts ...ClientOption) error {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetStreamIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetStreamID",
		Method:             "GET",
		PathPattern:        "/stream/{id}",
		ProducesMediaTypes: []string{"text/event-stream"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetStreamIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	_, err := a.transport.Submit(op)
	if err != nil {
		return err
	}
	return nil
}

/*
PostRoomID posts to room

Post a message to a room
*/
func (a *Client) PostRoomID(params *PostRoomIDParams, opts ...ClientOption) (*PostRoomIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostRoomIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostRoomID",
		Method:             "POST",
		PathPattern:        "/room/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &PostRoomIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostRoomIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostRoomID: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
