// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetStreamIDParams creates a new GetStreamIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetStreamIDParams() *GetStreamIDParams {
	return &GetStreamIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetStreamIDParamsWithTimeout creates a new GetStreamIDParams object
// with the ability to set a timeout on a request.
func NewGetStreamIDParamsWithTimeout(timeout time.Duration) *GetStreamIDParams {
	return &GetStreamIDParams{
		timeout: timeout,
	}
}

// NewGetStreamIDParamsWithContext creates a new GetStreamIDParams object
// with the ability to set a context for a request.
func NewGetStreamIDParamsWithContext(ctx context.Context) *GetStreamIDParams {
	return &GetStreamIDParams{
		Context: ctx,
	}
}

// NewGetStreamIDParamsWithHTTPClient creates a new GetStreamIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetStreamIDParamsWithHTTPClient(client *http.Client) *GetStreamIDParams {
	return &GetStreamIDParams{
		HTTPClient: client,
	}
}

/*
GetStreamIDParams contains all the parameters to send to the API endpoint

	for the get stream ID operation.

	Typically these are written to a http.Request.
*/
type GetStreamIDParams struct {

	/* ID.

	   Room ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get stream ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStreamIDParams) WithDefaults() *GetStreamIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get stream ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetStreamIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get stream ID params
func (o *GetStreamIDParams) WithTimeout(timeout time.Duration) *GetStreamIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get stream ID params
func (o *GetStreamIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get stream ID params
func (o *GetStreamIDParams) WithContext(ctx context.Context) *GetStreamIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get stream ID params
func (o *GetStreamIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get stream ID params
func (o *GetStreamIDParams) WithHTTPClient(client *http.Client) *GetStreamIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get stream ID params
func (o *GetStreamIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get stream ID params
func (o *GetStreamIDParams) WithID(id string) *GetStreamIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get stream ID params
func (o *GetStreamIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetStreamIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
