// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"rc-client/models"
)

// NewPostRoomIDParams creates a new PostRoomIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRoomIDParams() *PostRoomIDParams {
	return &PostRoomIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRoomIDParamsWithTimeout creates a new PostRoomIDParams object
// with the ability to set a timeout on a request.
func NewPostRoomIDParamsWithTimeout(timeout time.Duration) *PostRoomIDParams {
	return &PostRoomIDParams{
		timeout: timeout,
	}
}

// NewPostRoomIDParamsWithContext creates a new PostRoomIDParams object
// with the ability to set a context for a request.
func NewPostRoomIDParamsWithContext(ctx context.Context) *PostRoomIDParams {
	return &PostRoomIDParams{
		Context: ctx,
	}
}

// NewPostRoomIDParamsWithHTTPClient creates a new PostRoomIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRoomIDParamsWithHTTPClient(client *http.Client) *PostRoomIDParams {
	return &PostRoomIDParams{
		HTTPClient: client,
	}
}

/*
PostRoomIDParams contains all the parameters to send to the API endpoint

	for the post room ID operation.

	Typically these are written to a http.Request.
*/
type PostRoomIDParams struct {

	/* ID.

	   Room ID
	*/
	ID string

	/* MessageInput.

	   Message body
	*/
	MessageInput *models.AdapterMessageInput

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post room ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRoomIDParams) WithDefaults() *PostRoomIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post room ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRoomIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post room ID params
func (o *PostRoomIDParams) WithTimeout(timeout time.Duration) *PostRoomIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post room ID params
func (o *PostRoomIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post room ID params
func (o *PostRoomIDParams) WithContext(ctx context.Context) *PostRoomIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post room ID params
func (o *PostRoomIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post room ID params
func (o *PostRoomIDParams) WithHTTPClient(client *http.Client) *PostRoomIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post room ID params
func (o *PostRoomIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post room ID params
func (o *PostRoomIDParams) WithID(id string) *PostRoomIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post room ID params
func (o *PostRoomIDParams) SetID(id string) {
	o.ID = id
}

// WithMessageInput adds the messageInput to the post room ID params
func (o *PostRoomIDParams) WithMessageInput(messageInput *models.AdapterMessageInput) *PostRoomIDParams {
	o.SetMessageInput(messageInput)
	return o
}

// SetMessageInput adds the messageInput to the post room ID params
func (o *PostRoomIDParams) SetMessageInput(messageInput *models.AdapterMessageInput) {
	o.MessageInput = messageInput
}

// WriteToRequest writes these params to a swagger request
func (o *PostRoomIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.MessageInput != nil {
		if err := r.SetBodyParam(o.MessageInput); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
