// Code generated by go-swagger; DO NOT EDIT.

package chat

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"rc-client/models"
)

// PostRoomIDReader is a Reader for the PostRoomID structure.
type PostRoomIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRoomIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostRoomIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostRoomIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostRoomIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostRoomIDOK creates a PostRoomIDOK with default headers values
func NewPostRoomIDOK() *PostRoomIDOK {
	return &PostRoomIDOK{}
}

/*
PostRoomIDOK describes a response with status code 200, with default header values.

OK
*/
type PostRoomIDOK struct {
	Payload *models.AdapterResponse
}

// IsSuccess returns true when this post room Id o k response has a 2xx status code
func (o *PostRoomIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post room Id o k response has a 3xx status code
func (o *PostRoomIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post room Id o k response has a 4xx status code
func (o *PostRoomIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post room Id o k response has a 5xx status code
func (o *PostRoomIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post room Id o k response a status code equal to that given
func (o *PostRoomIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostRoomIDOK) Error() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdOK  %+v", 200, o.Payload)
}

func (o *PostRoomIDOK) String() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdOK  %+v", 200, o.Payload)
}

func (o *PostRoomIDOK) GetPayload() *models.AdapterResponse {
	return o.Payload
}

func (o *PostRoomIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdapterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoomIDBadRequest creates a PostRoomIDBadRequest with default headers values
func NewPostRoomIDBadRequest() *PostRoomIDBadRequest {
	return &PostRoomIDBadRequest{}
}

/*
PostRoomIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostRoomIDBadRequest struct {
	Payload *models.AdapterHTTPError
}

// IsSuccess returns true when this post room Id bad request response has a 2xx status code
func (o *PostRoomIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post room Id bad request response has a 3xx status code
func (o *PostRoomIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post room Id bad request response has a 4xx status code
func (o *PostRoomIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post room Id bad request response has a 5xx status code
func (o *PostRoomIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post room Id bad request response a status code equal to that given
func (o *PostRoomIDBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *PostRoomIDBadRequest) Error() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdBadRequest  %+v", 400, o.Payload)
}

func (o *PostRoomIDBadRequest) String() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdBadRequest  %+v", 400, o.Payload)
}

func (o *PostRoomIDBadRequest) GetPayload() *models.AdapterHTTPError {
	return o.Payload
}

func (o *PostRoomIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdapterHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRoomIDInternalServerError creates a PostRoomIDInternalServerError with default headers values
func NewPostRoomIDInternalServerError() *PostRoomIDInternalServerError {
	return &PostRoomIDInternalServerError{}
}

/*
PostRoomIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostRoomIDInternalServerError struct {
	Payload *models.AdapterHTTPError
}

// IsSuccess returns true when this post room Id internal server error response has a 2xx status code
func (o *PostRoomIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post room Id internal server error response has a 3xx status code
func (o *PostRoomIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post room Id internal server error response has a 4xx status code
func (o *PostRoomIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post room Id internal server error response has a 5xx status code
func (o *PostRoomIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post room Id internal server error response a status code equal to that given
func (o *PostRoomIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *PostRoomIDInternalServerError) Error() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PostRoomIDInternalServerError) String() string {
	return fmt.Sprintf("[POST /room/{id}][%d] postRoomIdInternalServerError  %+v", 500, o.Payload)
}

func (o *PostRoomIDInternalServerError) GetPayload() *models.AdapterHTTPError {
	return o.Payload
}

func (o *PostRoomIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AdapterHTTPError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
