version: '3.8'

services:
  server:
    build: ./server
    container_name: dc-realtime-server
    ports:
      - 5000:${SERVER_PORT}

  client:
    build: ./client
    container_name: dc-realtime-client
    tty: true
    environment:
      - HOST=server:${SERVER_PORT}

networks:
  default:
    external: true
    name: dc-realtime-network