// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdapterMessageInput adapter message input
//
// swagger:model adapter.messageInput
type AdapterMessageInput struct {

	// data
	Data string `json:"data,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this adapter message input
func (m *AdapterMessageInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this adapter message input based on context it is used
func (m *AdapterMessageInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdapterMessageInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdapterMessageInput) UnmarshalBinary(b []byte) error {
	var res AdapterMessageInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
