// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AdapterResponse adapter response
//
// swagger:model adapter.response
type AdapterResponse struct {

	// data
	Data string `json:"data,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// success
	Success bool `json:"success,omitempty"`
}

// Validate validates this adapter response
func (m *AdapterResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this adapter response based on context it is used
func (m *AdapterResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AdapterResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AdapterResponse) UnmarshalBinary(b []byte) error {
	var res AdapterResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
