basePath: /api
definitions:
  adapter.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  adapter.messageInput:
    properties:
      data:
        type: string
      userId:
        type: string
    type: object
  adapter.response:
    properties:
      data:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Realtime chat api using channels.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Realtime Chat API
  version: "0.1"
paths:
  /room/{id}:
    delete:
      description: Delete the room
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapter.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/adapter.HTTPError'
      summary: Delete a room
      tags:
      - chat
    post:
      consumes:
      - application/json
      description: Post a message to a room
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      - description: Message body
        in: body
        name: messageInput
        required: true
        schema:
          $ref: '#/definitions/adapter.messageInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapter.response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/adapter.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/adapter.HTTPError'
      summary: Post to room
      tags:
      - chat
  /stream/{id}:
    get:
      description: Stream messages from a room
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - text/event-stream
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/adapter.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/adapter.HTTPError'
      summary: Stream messages
      tags:
      - chat
swagger: "2.0"
